Consultoría SIG:
  - name: mapping
    label: Cartografía
    short_description: Diseño y creación de mapas.
    #details: Preparamos vuestros mapas personalizados y adaptados a vuestras  necesidades.

  - name: data_management
    label: Gestión de datos
    short_description: Bases de datos y procesamiento.

  - name: automation
    label: Automatización de procesos
    short_description: Desarrollo de scripts para la optimización de recursos.

  - name: web_development
    label: Aplicaciones Web
    short_description: Desarrollo de aplicaciones web.

  - name: mdc
    label: Recopilación de datos	móvil
    short_description: Apoyo para la Recopilación de datos con dispositivos móviles.

  - name: training
    label: Formación SIG
    short_description: Formación en Sistemas de Información Geografica para empresas.

Tecnologías:
  - name: qgis
    label: QGIS
    logo: assets/img/svg/qgis.svg
    url: https://www.qgis.org/
    #short_description:

  - name: esri
    label: Esri
    logo: assets/img/svg/esri.svg
    url: https://www.esri.com/
    #short_description:

  - name: postgresql
    label: PostgreSQL
    logo: assets/img/svg/Postgresql_elephant.svg
    url: https://www.postgresql.org/
    #short_description:

  - name: postgis
    label: PostGIS
    logo: assets/img/png/postgis_logo_square.png
    url: https://postgis.net/
    #short_description:

  - name: python
    label: Python
    logo: assets/img/svg/python-logo-only.svg
    url: https://www.python.org/
    #short_description:

  - name: javascript
    label: JavaScript
    logo: assets/img/svg/javascript.svg
    url: https://developer.mozilla.org/es/docs/Web/JavaScript
    #short_description:
    hide_in_services: false

  - name: kobotoolbox
    label: KoboToolbox
    logo: assets/img/svg/kobotoolbox_logo_default_for-light-bg.svg
    url: https://kobotoolbox.org/
    hide_in_services: true

  - name: observablehq
    label: Observable Framework
    logo:
    url: https://observablehq.com/framework/
    hide_in_services: true

Otros servicios:
